server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}
mybatis:
  #mapper configuration
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #start camel format
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # set JWT encryption key
    admin-secret-key: itcast
    # set expired time
    admin-ttl: 72000000
    # set the name comes from frontend
    admin-token-name: token

    # set JWT encryption key
    user-secret-key: itheima
    # set expired time
    user-ttl: 72000000
    # set the name comes from frontend
    user-token-name: authentication


  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}

  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}

  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: UEBQm9c3KZ5Lrs02C2q